module.exports = {
  nombre: "Buenos Aires",
  distanciaEntreProvincias: [
    { provincia: "Catamarca", distancia: 1158 },
    { provincia: "Chaco", distancia: 1023 },
    { provincia: "Chubut", distancia: 1407 },
    { provincia: "Córdoba", distancia: 695 },
    { provincia: "Corrientes", distancia: 1002 },
    { provincia: "Entre Ríos", distancia: 494 },
    { provincia: "Formosa", distancia: 1176 },
    { provincia: "Jujuy", distancia: 1534 },
    { provincia: "La Pampa", distancia: 620 },
    { provincia: "La Rioja", distancia: 1158 },
    { provincia: "Mendoza", distancia: 1048 },
    { provincia: "Misiones", distancia: 1060 },
    { provincia: "Neuquén", distancia: 1157 },
    { provincia: "Río Negro", distancia: 1212 },
    { provincia: "Salta", distancia: 1491 },
    { provincia: "San Juan", distancia: 1114 },
    { provincia: "San Luis", distancia: 790 },
    { provincia: "Santa Cruz", distancia: 2092 },
    { provincia: "Santa Fe", distancia: 478 },
    { provincia: "Santiago del Estero", distancia: 1045 },
    { provincia: "Tierra del Fuego", distancia: 2610 },
    { provincia: "Tucumán", distancia: 1316 },
  ],
};
