let cordoba = {
  nombre: "Córdoba",
  distanciaEntreProvincias: [
    { provincia: "Buenos Aires", distancia: 695 },
    { provincia: "Catamarca", distancia: 426 },
    { provincia: "Chaco", distancia: 607 },
    { provincia: "Chubut", distancia: 1137 },
    { provincia: "Corrientes", distancia: 724 },
    { provincia: "Entre Ríos", distancia: 401 },
    { provincia: "Formosa", distancia: 813 },
    { provincia: "Jujuy", distancia: 1191 },
    { provincia: "La Pampa", distancia: 342 },
    { provincia: "La Rioja", distancia: 448 },
    { provincia: "Mendoza", distancia: 470 },
    { provincia: "Misiones", distancia: 1034 },
    { provincia: "Neuquén", distancia: 887 },
    { provincia: "Río Negro", distancia: 832 },
    { provincia: "Salta", distancia: 854 },
    { provincia: "San Juan", distancia: 579 },
    { provincia: "San Luis", distancia: 291 },
    { provincia: "Santa Cruz", distancia: 2388 },
    { provincia: "Santa Fe", distancia: 401 },
    { provincia: "Santiago del Estero", distancia: 654 },
    { provincia: "Tierra del Fuego", distancia: 3008 },
    { provincia: "Tucumán", distancia: 998 },
  ],
};
module.exports = cordoba;
