const corrientes = {
  nombre: "Corrientes",
  distanciaEntreProvincias: [
    { provincia: "Buenos Aires", distancia: 1002 },
    { provincia: "Catamarca", distancia: 762 },
    { provincia: "Chaco", distancia: 241 },
    { provincia: "Chubut", distancia: 2112 },
    { provincia: "Córdoba", distancia: 724 },
    { provincia: "Entre Ríos", distancia: 446 },
    { provincia: "Formosa", distancia: 327 },
    { provincia: "Jujuy", distancia: 740 },
    { provincia: "La Pampa", distancia: 1066 },
    { provincia: "La Rioja", distancia: 366 },
    { provincia: "Mendoza", distancia: 1007 },
    { provincia: "Misiones", distancia: 228 },
    { provincia: "Neuquén", distancia: 1382 },
    { provincia: "Río Negro", distancia: 1437 },
    { provincia: "Salta", distancia: 641 },
    { provincia: "San Juan", distancia: 1355 },
    { provincia: "San Luis", distancia: 893 },
    { provincia: "Santa Cruz", distancia: 2784 },
    { provincia: "Santa Fe", distancia: 452 },
    { provincia: "Santiago del Estero", distancia: 634 },
    { provincia: "Tierra del Fuego", distancia: 3830 },
    { provincia: "Tucumán", distancia: 701 },
  ],
};
module.exports = corrientes;
