// En el archivo provincias.js
module.exports = {
  "Buenos Aires": require("./buenosAires"),
  Catamarca: require("./catamarca"),
  Chaco: require("./chaco"),
  Chubut: require("./chubut"),
  Córdoba: require("./cordoba"),
  Corrientes: require("./corrientes"),
  "Entre Ríos": require("./entreRios"),
  Formosa: require("./formosa"),
  Jujuy: require("./jujuy"),
  "La Rioja": require("./laRioja"),
  "La Pampa": require("./laPampa"),
  Mendoza: require("./mendoza"),
  Misiones: require("./misiones"),
  Neuquén: require("./neuquen"),
  "Río Negro": require("./rioNegro"),
  Salta: require("./salta"),
  "San Juan": require("./sanJuan"),
  "San Luis": require("./sanLuis"),
  "Santa Cruz": require("./santaCruz"),
  "Santa Fe": require("./santaFe"),
  "Santiago del Estero": require("./santiagoDelEstero"),
  "Tierra del Fuego": require("./tierraDelFuego"),
  Tucumán: require("./tucuman"),
};
