const mendoza = {
  nombre: "Mendoza",
  distanciaEntreProvincias: [
    { provincia: "Buenos Aires", distancia: 1048 },
    { provincia: "Catamarca", distancia: 627 },
    { provincia: "Chaco", distancia: 1088 },
    { provincia: "Chubut", distancia: 1420 },
    { provincia: "Córdoba", distancia: 470 },
    { provincia: "Corrientes", distancia: 1007 },
    { provincia: "Entre Ríos", distancia: 1041 },
    { provincia: "Formosa", distancia: 1436 },
    { provincia: "Jujuy", distancia: 1384 },
    { provincia: "La Pampa", distancia: 428 },
    { provincia: "La Rioja", distancia: 641 },
    { provincia: "Misiones", distancia: 1622 },
    { provincia: "Neuquén", distancia: 851 },
    { provincia: "Río Negro", distancia: 906 },
    { provincia: "Salta", distancia: 1097 },
    { provincia: "San Juan", distancia: 166 },
    { provincia: "San Luis", distancia: 261 },
    { provincia: "Santa Cruz", distancia: 2462 },
    { provincia: "Santa Fe", distancia: 1042 },
    { provincia: "Santiago del Estero", distancia: 861 },
    { provincia: "Tierra del Fuego", distancia: 3108 },
    { provincia: "Tucumán", distancia: 790 },
  ],
};
module.exports = mendoza;
