const tierraDelFuego = {
  nombre: "Tierra del Fuego",
  distanciaEntreProvincias: [
    { provincia: "Buenos Aires", distancia: 2610 },
    { provincia: "Catamarca", distancia: 3120 },
    { provincia: "Chaco", distancia: 3911 },
    { provincia: "Chubut", distancia: 1640 },
    { provincia: "Córdoba", distancia: 3008 },
    { provincia: "Corrientes", distancia: 3830 },
    { provincia: "Entre Ríos", distancia: 3314 },
    { provincia: "Formosa", distancia: 3800 },
    { provincia: "Jujuy", distancia: 3900 },
    { provincia: "La Pampa", distancia: 2500 },
    { provincia: "La Rioja", distancia: 3349 },
    { provincia: "Mendoza", distancia: 3108 },
    { provincia: "Misiones", distancia: 3568 },
    { provincia: "Neuquén", distancia: 2668 },
    { provincia: "Río Negro", distancia: 1500 },
    { provincia: "Salta", distancia: 3900 },
    { provincia: "San Juan", distancia: 3453 },
    { provincia: "San Luis", distancia: 3133 },
    { provincia: "Santa Cruz", distancia: 1046 },
    { provincia: "Santa Fe", distancia: 3457 },
    { provincia: "Santiago del Estero", distancia: 3706 },
    { provincia: "Tucumán", distancia: 3818 },
  ],
};
module.exports = tierraDelFuego;
